# Generated by Django 4.0.3 on 2022-03-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveads',
            options={'verbose_name': 'Архивное объявление', 'verbose_name_plural': 'Архивные объявления'},
        ),
    ]
