# Generated by Django 4.0.3 on 2022-03-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_archiveads_options_alter_picture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveads',
            options={'verbose_name': 'Архивное объявление', 'verbose_name_plural': 'Архивные объявления'},
        ),
    ]
