# Generated by Django 4.0.3 on 2022-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_archiveads_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='type_ad',
            field=models.IntegerField(choices=[(0, 'АРХИВИРОВАННОЕ'), (1, 'НЕАРХИВИРОВАННОЕ')], default=1, verbose_name='Тип  объявления'),
        ),
    ]
